export { default as Card } from './Card/Card'
export { default as Header } from './Header/Header'
export { default as Loader } from './Loader/Loader'
export { default as Page } from './Page/Page'
export { default as Pagination } from './Pagination/Pagination'
export { default as Sidebar } from './Sidebar/Sidebar'
export { default as Tabs } from './Tabs/Tabs'
